version: v1alpha1
condition:
  regex:
    principal_include:
    principal_exclude:
backend:
  address:
  insecure_enabled: false
  impersonate_account:
security_context:
  from_raw_jwt:

rules:
- selector: "*"
  directive: AUDIT_REQUEST_AND_RESPONSE