// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: talker.proto

package com.abcxyz.lumberjack.test.talker;

public interface AdditionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:abcxyz.test.AdditionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 addend = 1;</code>
   * @return The addend.
   */
  int getAddend();
}
