// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: talker.proto

package com.abcxyz.lumberjack.test.talker;

public interface AdditionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:abcxyz.test.AdditionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 sum = 1;</code>
   * @return The sum.
   */
  long getSum();
}
