// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: talker.proto

package com.abcxyz.lumberjack.test.talker;

/**
 * Protobuf type {@code abcxyz.test.AdditionRequest}
 */
public final class AdditionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:abcxyz.test.AdditionRequest)
    AdditionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdditionRequest.newBuilder() to construct.
  private AdditionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdditionRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdditionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AdditionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            addend_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_AdditionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_AdditionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.abcxyz.lumberjack.test.talker.AdditionRequest.class, com.abcxyz.lumberjack.test.talker.AdditionRequest.Builder.class);
  }

  public static final int ADDEND_FIELD_NUMBER = 1;
  private int addend_;
  /**
   * <code>uint32 addend = 1;</code>
   * @return The addend.
   */
  @java.lang.Override
  public int getAddend() {
    return addend_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (addend_ != 0) {
      output.writeUInt32(1, addend_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (addend_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, addend_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.abcxyz.lumberjack.test.talker.AdditionRequest)) {
      return super.equals(obj);
    }
    com.abcxyz.lumberjack.test.talker.AdditionRequest other = (com.abcxyz.lumberjack.test.talker.AdditionRequest) obj;

    if (getAddend()
        != other.getAddend()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ADDEND_FIELD_NUMBER;
    hash = (53 * hash) + getAddend();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.abcxyz.lumberjack.test.talker.AdditionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.abcxyz.lumberjack.test.talker.AdditionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code abcxyz.test.AdditionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:abcxyz.test.AdditionRequest)
      com.abcxyz.lumberjack.test.talker.AdditionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_AdditionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_AdditionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.abcxyz.lumberjack.test.talker.AdditionRequest.class, com.abcxyz.lumberjack.test.talker.AdditionRequest.Builder.class);
    }

    // Construct using com.abcxyz.lumberjack.test.talker.AdditionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      addend_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_AdditionRequest_descriptor;
    }

    @java.lang.Override
    public com.abcxyz.lumberjack.test.talker.AdditionRequest getDefaultInstanceForType() {
      return com.abcxyz.lumberjack.test.talker.AdditionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.abcxyz.lumberjack.test.talker.AdditionRequest build() {
      com.abcxyz.lumberjack.test.talker.AdditionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.abcxyz.lumberjack.test.talker.AdditionRequest buildPartial() {
      com.abcxyz.lumberjack.test.talker.AdditionRequest result = new com.abcxyz.lumberjack.test.talker.AdditionRequest(this);
      result.addend_ = addend_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.abcxyz.lumberjack.test.talker.AdditionRequest) {
        return mergeFrom((com.abcxyz.lumberjack.test.talker.AdditionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.abcxyz.lumberjack.test.talker.AdditionRequest other) {
      if (other == com.abcxyz.lumberjack.test.talker.AdditionRequest.getDefaultInstance()) return this;
      if (other.getAddend() != 0) {
        setAddend(other.getAddend());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.abcxyz.lumberjack.test.talker.AdditionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.abcxyz.lumberjack.test.talker.AdditionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int addend_ ;
    /**
     * <code>uint32 addend = 1;</code>
     * @return The addend.
     */
    @java.lang.Override
    public int getAddend() {
      return addend_;
    }
    /**
     * <code>uint32 addend = 1;</code>
     * @param value The addend to set.
     * @return This builder for chaining.
     */
    public Builder setAddend(int value) {
      
      addend_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 addend = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddend() {
      
      addend_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:abcxyz.test.AdditionRequest)
  }

  // @@protoc_insertion_point(class_scope:abcxyz.test.AdditionRequest)
  private static final com.abcxyz.lumberjack.test.talker.AdditionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.abcxyz.lumberjack.test.talker.AdditionRequest();
  }

  public static com.abcxyz.lumberjack.test.talker.AdditionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdditionRequest>
      PARSER = new com.google.protobuf.AbstractParser<AdditionRequest>() {
    @java.lang.Override
    public AdditionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AdditionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdditionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdditionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.abcxyz.lumberjack.test.talker.AdditionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

