// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: talker.proto

package com.abcxyz.lumberjack.test.talker;

/**
 * Protobuf type {@code abcxyz.test.AdditionResponse}
 */
public final class AdditionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:abcxyz.test.AdditionResponse)
    AdditionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdditionResponse.newBuilder() to construct.
  private AdditionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdditionResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdditionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AdditionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            sum_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_AdditionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_AdditionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.abcxyz.lumberjack.test.talker.AdditionResponse.class, com.abcxyz.lumberjack.test.talker.AdditionResponse.Builder.class);
  }

  public static final int SUM_FIELD_NUMBER = 1;
  private long sum_;
  /**
   * <code>uint64 sum = 1;</code>
   * @return The sum.
   */
  @java.lang.Override
  public long getSum() {
    return sum_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sum_ != 0L) {
      output.writeUInt64(1, sum_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sum_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, sum_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.abcxyz.lumberjack.test.talker.AdditionResponse)) {
      return super.equals(obj);
    }
    com.abcxyz.lumberjack.test.talker.AdditionResponse other = (com.abcxyz.lumberjack.test.talker.AdditionResponse) obj;

    if (getSum()
        != other.getSum()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSum());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.abcxyz.lumberjack.test.talker.AdditionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.abcxyz.lumberjack.test.talker.AdditionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.abcxyz.lumberjack.test.talker.AdditionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code abcxyz.test.AdditionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:abcxyz.test.AdditionResponse)
      com.abcxyz.lumberjack.test.talker.AdditionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_AdditionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_AdditionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.abcxyz.lumberjack.test.talker.AdditionResponse.class, com.abcxyz.lumberjack.test.talker.AdditionResponse.Builder.class);
    }

    // Construct using com.abcxyz.lumberjack.test.talker.AdditionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sum_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_AdditionResponse_descriptor;
    }

    @java.lang.Override
    public com.abcxyz.lumberjack.test.talker.AdditionResponse getDefaultInstanceForType() {
      return com.abcxyz.lumberjack.test.talker.AdditionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.abcxyz.lumberjack.test.talker.AdditionResponse build() {
      com.abcxyz.lumberjack.test.talker.AdditionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.abcxyz.lumberjack.test.talker.AdditionResponse buildPartial() {
      com.abcxyz.lumberjack.test.talker.AdditionResponse result = new com.abcxyz.lumberjack.test.talker.AdditionResponse(this);
      result.sum_ = sum_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.abcxyz.lumberjack.test.talker.AdditionResponse) {
        return mergeFrom((com.abcxyz.lumberjack.test.talker.AdditionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.abcxyz.lumberjack.test.talker.AdditionResponse other) {
      if (other == com.abcxyz.lumberjack.test.talker.AdditionResponse.getDefaultInstance()) return this;
      if (other.getSum() != 0L) {
        setSum(other.getSum());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.abcxyz.lumberjack.test.talker.AdditionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.abcxyz.lumberjack.test.talker.AdditionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long sum_ ;
    /**
     * <code>uint64 sum = 1;</code>
     * @return The sum.
     */
    @java.lang.Override
    public long getSum() {
      return sum_;
    }
    /**
     * <code>uint64 sum = 1;</code>
     * @param value The sum to set.
     * @return This builder for chaining.
     */
    public Builder setSum(long value) {
      
      sum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 sum = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSum() {
      
      sum_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:abcxyz.test.AdditionResponse)
  }

  // @@protoc_insertion_point(class_scope:abcxyz.test.AdditionResponse)
  private static final com.abcxyz.lumberjack.test.talker.AdditionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.abcxyz.lumberjack.test.talker.AdditionResponse();
  }

  public static com.abcxyz.lumberjack.test.talker.AdditionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdditionResponse>
      PARSER = new com.google.protobuf.AbstractParser<AdditionResponse>() {
    @java.lang.Override
    public AdditionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AdditionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdditionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdditionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.abcxyz.lumberjack.test.talker.AdditionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

