// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: talker.proto

package com.abcxyz.lumberjack.test.talker;

public interface FibonacciResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:abcxyz.test.FibonacciResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 position = 1;</code>
   * @return The position.
   */
  int getPosition();

  /**
   * <code>uint32 value = 2;</code>
   * @return The value.
   */
  int getValue();
}
