// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: talker.proto

package com.abcxyz.lumberjack.test.talker;

public interface FibonacciRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:abcxyz.test.FibonacciRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 places = 1;</code>
   * @return The places.
   */
  int getPlaces();
}
