// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: talker.proto

package com.abcxyz.lumberjack.test.talker;

/**
 * Protobuf type {@code abcxyz.test.FibonacciResponse}
 */
public final class FibonacciResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:abcxyz.test.FibonacciResponse)
    FibonacciResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FibonacciResponse.newBuilder() to construct.
  private FibonacciResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FibonacciResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FibonacciResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FibonacciResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            position_ = input.readUInt32();
            break;
          }
          case 16: {

            value_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_FibonacciResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_FibonacciResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.abcxyz.lumberjack.test.talker.FibonacciResponse.class, com.abcxyz.lumberjack.test.talker.FibonacciResponse.Builder.class);
  }

  public static final int POSITION_FIELD_NUMBER = 1;
  private int position_;
  /**
   * <code>uint32 position = 1;</code>
   * @return The position.
   */
  @java.lang.Override
  public int getPosition() {
    return position_;
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private int value_;
  /**
   * <code>uint32 value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public int getValue() {
    return value_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (position_ != 0) {
      output.writeUInt32(1, position_);
    }
    if (value_ != 0) {
      output.writeUInt32(2, value_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (position_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, position_);
    }
    if (value_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, value_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.abcxyz.lumberjack.test.talker.FibonacciResponse)) {
      return super.equals(obj);
    }
    com.abcxyz.lumberjack.test.talker.FibonacciResponse other = (com.abcxyz.lumberjack.test.talker.FibonacciResponse) obj;

    if (getPosition()
        != other.getPosition()) return false;
    if (getValue()
        != other.getValue()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + getPosition();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.abcxyz.lumberjack.test.talker.FibonacciResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code abcxyz.test.FibonacciResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:abcxyz.test.FibonacciResponse)
      com.abcxyz.lumberjack.test.talker.FibonacciResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_FibonacciResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_FibonacciResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.abcxyz.lumberjack.test.talker.FibonacciResponse.class, com.abcxyz.lumberjack.test.talker.FibonacciResponse.Builder.class);
    }

    // Construct using com.abcxyz.lumberjack.test.talker.FibonacciResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      position_ = 0;

      value_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.abcxyz.lumberjack.test.talker.TalkerProto.internal_static_abcxyz_test_FibonacciResponse_descriptor;
    }

    @java.lang.Override
    public com.abcxyz.lumberjack.test.talker.FibonacciResponse getDefaultInstanceForType() {
      return com.abcxyz.lumberjack.test.talker.FibonacciResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.abcxyz.lumberjack.test.talker.FibonacciResponse build() {
      com.abcxyz.lumberjack.test.talker.FibonacciResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.abcxyz.lumberjack.test.talker.FibonacciResponse buildPartial() {
      com.abcxyz.lumberjack.test.talker.FibonacciResponse result = new com.abcxyz.lumberjack.test.talker.FibonacciResponse(this);
      result.position_ = position_;
      result.value_ = value_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.abcxyz.lumberjack.test.talker.FibonacciResponse) {
        return mergeFrom((com.abcxyz.lumberjack.test.talker.FibonacciResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.abcxyz.lumberjack.test.talker.FibonacciResponse other) {
      if (other == com.abcxyz.lumberjack.test.talker.FibonacciResponse.getDefaultInstance()) return this;
      if (other.getPosition() != 0) {
        setPosition(other.getPosition());
      }
      if (other.getValue() != 0) {
        setValue(other.getValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.abcxyz.lumberjack.test.talker.FibonacciResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.abcxyz.lumberjack.test.talker.FibonacciResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int position_ ;
    /**
     * <code>uint32 position = 1;</code>
     * @return The position.
     */
    @java.lang.Override
    public int getPosition() {
      return position_;
    }
    /**
     * <code>uint32 position = 1;</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(int value) {
      
      position_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 position = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      
      position_ = 0;
      onChanged();
      return this;
    }

    private int value_ ;
    /**
     * <code>uint32 value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public int getValue() {
      return value_;
    }
    /**
     * <code>uint32 value = 2;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(int value) {
      
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      
      value_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:abcxyz.test.FibonacciResponse)
  }

  // @@protoc_insertion_point(class_scope:abcxyz.test.FibonacciResponse)
  private static final com.abcxyz.lumberjack.test.talker.FibonacciResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.abcxyz.lumberjack.test.talker.FibonacciResponse();
  }

  public static com.abcxyz.lumberjack.test.talker.FibonacciResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FibonacciResponse>
      PARSER = new com.google.protobuf.AbstractParser<FibonacciResponse>() {
    @java.lang.Override
    public FibonacciResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FibonacciResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FibonacciResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FibonacciResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.abcxyz.lumberjack.test.talker.FibonacciResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

