// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: talker.proto

package com.abcxyz.lumberjack.test.talker;

public final class TalkerProto {
  private TalkerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_abcxyz_test_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_abcxyz_test_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_abcxyz_test_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_abcxyz_test_HelloResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_abcxyz_test_WhisperRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_abcxyz_test_WhisperRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_abcxyz_test_WhisperResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_abcxyz_test_WhisperResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_abcxyz_test_ByeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_abcxyz_test_ByeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_abcxyz_test_ByeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_abcxyz_test_ByeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_abcxyz_test_FibonacciRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_abcxyz_test_FibonacciRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_abcxyz_test_FibonacciResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_abcxyz_test_FibonacciResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_abcxyz_test_AdditionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_abcxyz_test_AdditionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_abcxyz_test_AdditionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_abcxyz_test_AdditionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014talker.proto\022\013abcxyz.test\"/\n\014HelloRequ" +
      "est\022\016\n\006target\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\" \n\r" +
      "HelloResponse\022\017\n\007message\030\001 \001(\t\"1\n\016Whispe" +
      "rRequest\022\016\n\006target\030\001 \001(\t\022\017\n\007message\030\002 \001(" +
      "\t\"\"\n\017WhisperResponse\022\017\n\007message\030\001 \001(\t\"-\n" +
      "\nByeRequest\022\016\n\006target\030\001 \001(\t\022\017\n\007message\030\002" +
      " \001(\t\"\036\n\013ByeResponse\022\017\n\007message\030\001 \001(\t\"\"\n\020" +
      "FibonacciRequest\022\016\n\006places\030\001 \001(\r\"4\n\021Fibo" +
      "nacciResponse\022\020\n\010position\030\001 \001(\r\022\r\n\005value" +
      "\030\002 \001(\r\"!\n\017AdditionRequest\022\016\n\006addend\030\001 \001(" +
      "\r\"\037\n\020AdditionResponse\022\013\n\003sum\030\001 \001(\0042\341\002\n\006T" +
      "alker\022>\n\005Hello\022\031.abcxyz.test.HelloReques" +
      "t\032\032.abcxyz.test.HelloResponse\022D\n\007Whisper" +
      "\022\033.abcxyz.test.WhisperRequest\032\034.abcxyz.t" +
      "est.WhisperResponse\0228\n\003Bye\022\027.abcxyz.test" +
      ".ByeRequest\032\030.abcxyz.test.ByeResponse\022L\n" +
      "\tFibonacci\022\035.abcxyz.test.FibonacciReques" +
      "t\032\036.abcxyz.test.FibonacciResponse0\001\022I\n\010A" +
      "ddition\022\034.abcxyz.test.AdditionRequest\032\035." +
      "abcxyz.test.AdditionResponse(\001B{\n!com.ab" +
      "cxyz.lumberjack.test.talkerB\013TalkerProto" +
      "P\001ZGgithub.com/abcxyz/lumberjack/clients" +
      "/go/test/grpc-app/talkerpb;talkerpbb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_abcxyz_test_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_abcxyz_test_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_abcxyz_test_HelloRequest_descriptor,
        new java.lang.String[] { "Target", "Message", });
    internal_static_abcxyz_test_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_abcxyz_test_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_abcxyz_test_HelloResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_abcxyz_test_WhisperRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_abcxyz_test_WhisperRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_abcxyz_test_WhisperRequest_descriptor,
        new java.lang.String[] { "Target", "Message", });
    internal_static_abcxyz_test_WhisperResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_abcxyz_test_WhisperResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_abcxyz_test_WhisperResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_abcxyz_test_ByeRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_abcxyz_test_ByeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_abcxyz_test_ByeRequest_descriptor,
        new java.lang.String[] { "Target", "Message", });
    internal_static_abcxyz_test_ByeResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_abcxyz_test_ByeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_abcxyz_test_ByeResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_abcxyz_test_FibonacciRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_abcxyz_test_FibonacciRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_abcxyz_test_FibonacciRequest_descriptor,
        new java.lang.String[] { "Places", });
    internal_static_abcxyz_test_FibonacciResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_abcxyz_test_FibonacciResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_abcxyz_test_FibonacciResponse_descriptor,
        new java.lang.String[] { "Position", "Value", });
    internal_static_abcxyz_test_AdditionRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_abcxyz_test_AdditionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_abcxyz_test_AdditionRequest_descriptor,
        new java.lang.String[] { "Addend", });
    internal_static_abcxyz_test_AdditionResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_abcxyz_test_AdditionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_abcxyz_test_AdditionResponse_descriptor,
        new java.lang.String[] { "Sum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
