// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: talker.proto

package com.abcxyz.lumberjack.test.talker;

public interface WhisperRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:abcxyz.test.WhisperRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string target = 1;</code>
   * @return The target.
   */
  java.lang.String getTarget();
  /**
   * <code>string target = 1;</code>
   * @return The bytes for target.
   */
  com.google.protobuf.ByteString
      getTargetBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
