name: 'ci'
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

env:
  docker_registry: 'us-docker.pkg.dev'
  docker_tag: '${{ github.sha }}'
  docker_repo: 'us-docker.pkg.dev/lumberjack-ci-dev/images'
  wif_provider: 'projects/127752565609/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
  wif_service_account: 'github-wif-sa@lumberjack-ci-dev.iam.gserviceaccount.com'
  server_project_id: 'github-ci-server'
  client_project_id: 'github-ci-app-0'
  tf_state_bucket: 'lumberjack-ci-tfstate'
  bigquery_dataset_id: 'audit_logs.audit_abcxyz_data_access'

jobs:
  # GitHub actions that call other workflows cannot access environment variable information
  # in the 'with' input definition section due to the fact that the GitHub context information
  # is not availble. This job converts environment data into a json string that can be passed 
  # between workflows to work around this and provide a way to define all of the important variables
  # in a single place at the top of this file.
  # If the day comes that GitHub changes this we can eliminate this job and switch to direct environment
  # variable references as inputs to the 'sub workflows'.
  setup-environment:
    runs-on: 'ubuntu-latest'
    outputs:
      env-context: ${{ steps.encode-environment.outputs.env-context }}
    steps:
      - id: encode-environment
        run: |-
          jq -nc \
            --arg docker_registry ${{env.docker_registry}} \
            --arg docker_tag ${{env.docker_tag}} \
            --arg docker_repo ${{env.docker_repo}} \
            --arg wif_provider ${{env.wif_provider}} \
            --arg wif_service_account ${{env.wif_service_account}} \
            --arg server_project_id ${{env.server_project_id}} \
            --arg client_project_id ${{env.client_project_id}} \
            --arg tf_state_bucket ${{env.tf_state_bucket}} \
            --arg bigquery_dataset_id ${{env.bigquery_dataset_id}} \
            '{"docker_registry":$docker_registry,"docker_tag":$docker_tag,"docker_repo":$docker_repo,"wif_provider":$wif_provider,"wif_service_account":$wif_service_account,"server_project_id":$server_project_id,"client_project_id":$client_project_id,"tf_state_bucket":$tf_state_bucket,"bigquery_dataset_id":$bigquery_dataset_id}' \
            > env.json
          echo "::set-output name=env-context::$(jq tostring env.json)"

  lint:
    uses: ./.github/workflows/lint.yml

  unit:
    uses: ./.github/workflows/unit.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: [setup-environment, lint, unit]
    with:
      env-context: ${{ needs.setup-environment.outputs.env-context }}

  integration:
    uses: ./.github/workflows/integration.yml
    needs: [setup-environment, build]
    with:
      env-context: ${{ needs.setup-environment.outputs.env-context }}