name: 'cleanup'

on:
  pull_request:
    paths:
      - '.github/workflows/cleanup.yml'
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:

env:
  PROJECT_ID: 'github-ci-app-0'
  PROJECT_NUMBER: '638387980668'
  REGION: 'us-central1'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  # cleanup_cloudrun_services deletes all Cloud Run services that are more than
  # 5 days old, since sometimes services are not deleted during integration
  # tests.
  cleanup_cloudrun_services:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b' # ratchet:actions/checkout@v3

      - uses: 'google-github-actions/auth@c4799db9111fba4461e9f9da8732e5057b394f72' # ratchet:google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'gh-access-sa@lumberjack-dev-infra.iam.gserviceaccount.com'

      - uses: 'google-github-actions/setup-gcloud@ee9693ff89cdf73862b8a13988f6a71070e8fc58' # ratchet:google-github-actions/setup-gcloud@v0

      - name: 'Remove old Cloud Run services'
        shell: 'bash'
        run: |-
          gcloud config set core/project "${{ env.PROJECT_ID }}"
          gcloud config set run/region "{{ env.REGION }}"

          # List and delete all services that were deployed 5 days ago or later.
          (IFS=$'\n'; for NAME in $(gcloud run services list --format="value(name)" --filter="metadata.creationTimestamp < '-p5d'"); do
            echo "Deleting ${NAME}..."
            gcloud run services delete ${NAME} --quiet --async
          done)

  # cleanup_container_images deletes all untagged container images that are more
  # than 14 days old.
  cleanup_container_images:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b' # ratchet:actions/checkout@v3

      - uses: 'google-github-actions/auth@c4799db9111fba4461e9f9da8732e5057b394f72' # ratchet:google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'gh-access-sa@lumberjack-dev-infra.iam.gserviceaccount.com'

      - name: 'Remove old container images'
        uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli' # ratchet:exclude old image versions are removed
        with:
          args: >-
            -repo=us-docker.pkg.dev/lumberjack-dev-infra/images/lumberjack-server
            -repo=us-docker.pkg.dev/lumberjack-dev-infra/images/ljc-go-grpc
            -repo=us-docker.pkg.dev/lumberjack-dev-infra/images/ljc-go-http
            -repo=us-docker.pkg.dev/lumberjack-dev-infra/images/ljc-java-grpc
            -repo=us-docker.pkg.dev/lumberjack-dev-infra/images/ljc-java-http
            -grace=336h
            -tag-filter-any=(?i)[0-9a-f]{40}(-amd64|-arm64)?
