name: 'Cleanup'

on:
  push:
    paths:
      - '.github/workflows/cleanup.yml'
  pull_request:
    paths:
      - '.github/workflows/cleanup.yml'
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:

jobs:
  cleanup:
    env:
      PROJECT_ID: 'github-ci-app-0'
      PROJECT_NUMBER: '638387980668'
      REGION: 'us-central1'

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b' # ratchet:actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@ceee102ec2387dd9e844e01b530ccd4ec87ce955' # ratchet:google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'gh-access-sa@lumberjack-dev-infra.iam.gserviceaccount.com'

      - name: 'Install and configure gcloud'
        uses: 'google-github-actions/setup-gcloud@877d4953d2c70a0ba7ef3290ae968eb24af233bb' # ratchet:google-github-actions/setup-gcloud@v0

      - name: 'Remove old Cloud Run services'
        shell: 'bash'
        run: |-
          SINCE=$(date --date="5 days ago" +"%Y-%m-%d")
          echo "Fetching services to delete older than ${SINCE}..."

          TO_DELETE=( $(gcloud run services list \
            --project="${{ env.PROJECT_ID }}" \
            --region="${{ env.REGION }}" \
            --filter="metadata.creationTimestamp<${SINCE}" \
            --format="value(SERVICE)") )

          for SERVICE in "${TO_DELETE[@]}"; do
            echo "Deleting ${SERVICE}..."
            gcloud run services delete ${SERVICE} \
              --project="${{ env.PROJECT_ID }}" \
              --region="${{ env.REGION }}"
          done
