name: Cleanup old services runs.

on:
  push:
    branches:
    - erniecastro/cleanupWorkflow
  schedule:
  - cron: '0 0 */1 * *'


jobs:
  cleanup:
    name: Cleanup
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/638387980668/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'gh-access-sa@lumberjack-dev-infra.iam.gserviceaccount.com'
        token_format: 'access_token' # needed for workaround
    - id: gcloud
      name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Cleanup script
      env:
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      run: |
        gcloud auth configure-docker us-docker.pkg.dev
        ./scripts/cleanup_services.sh
