# Default action to pass required checks when no testable changes are made
name: CI - Default Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "terraform/**"
      - "clients/go/**"
      - "clients/java-logger/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "terraform/**"
      - "clients/go/**"
      - "clients/java-logger/**"

# If a new commit comes in, cancel the current action run.
concurrency:
  group: "${{github.workflow}}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Print No Tests
        run: 'echo "No testable files were changed."'
