name: Java Coverage

on:
  push:
    branches:
      - main
    paths:
      - 'clients/java-logger/**'
      - '.github/workflows/github-presubmit-java-cov.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'clients/java-logger/**'
      - '.github/workflows/github-presubmit-java-cov.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Download Maven
        run: |
          curl -sL https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip -o maven.zip
          apt-get update
          apt-get -y install unzip
          unzip -d /usr/share maven.zip
          rm maven.zip
          ln -s /usr/share/apache-maven-3.8.4/bin/mvn /usr/bin/mvn
          echo "M2_HOME=/usr/share/apache-maven-3.8.4" | tee -a /etc/environment
      - name: Run Coverage
        working-directory: ./clients/java-logger
        run: mvn test
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: './clients/java-logger/library/target/site/jacoco/jacoco.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
