name: 'Lint Go'

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/lint-go.yml'
      - '**.go'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/lint-go.yml'
      - '**.go'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    uses: 'abcxyz/pkg/.github/workflows/go-lint.yml@main'
    with:
      go_version: '1.18'
