name: 'release'
on:
  push:
    tags:
      - 'v*'
env:
  # .goreleaser.docker.yaml reads DOCKER_REPO
  DOCKER_REPO: 'us-docker.pkg.dev/abcxyz-artifacts/docker-images'
  WIF_PROVIDER: 'projects/638387980668/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
  WIF_SERVICE_ACCOUNT: 'gh-access-sa@lumberjack-dev-infra.iam.gserviceaccount.com'

# Don't cancel in progress since we don't want to have half-baked release.
concurrency: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'

jobs:
  ci-test:
    uses: 'abcxyz/lumberjack/.github/workflows/ci.yml@main' # ratchet:exclude

  image-release:
    # Run tests before the release
    needs: ['ci-test']
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18' # ratchet:docker/setup-qemu-action@v2
      - uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8' # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: 'actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f' # ratchet:actions/setup-go@v3
        with:
          go-version: '1.19'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@c4799db9111fba4461e9f9da8732e5057b394f72' # ratchet:google-github-actions/auth@v0
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
          token_format: 'access_token'
      - name: 'Authenticate to Artifact Registry'
        uses: 'docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a' # ratchet:docker/login-action@v2
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'us-docker.pkg.dev'
      - uses: 'goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757' # ratchet:goreleaser/goreleaser-action@v3
        with:
          version: 'v1.12.3' # Manually pinned
          args: 'release -f .goreleaser.docker.yaml --rm-dist'

  maven-release:
    # Run tests before the release
    needs: ['ci-test']
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8' # ratchet:actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d # ratchet:actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@c4799db9111fba4461e9f9da8732e5057b394f72' # ratchet:google-github-actions/auth@v0
      with:
        workload_identity_provider: '${{ env.WIF_PROVIDER }}'
        service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
        # The Artifact Registry maven wagon looks for Google Application Default Credentials.
        # https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools
    - name: 'Maven deploy'
      # Use git tag without prefix "v".
      # Even though Artifact Registry allows versions starts with "v",
      # Maven's convention is to have versions without "v".
      run: |-
        mvn clean deploy -Drevision=${${{ github.ref_name }}#v} -f clients/java-logger/library


  github-release:
    needs: ['image-release', 'maven-release']
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
      packages: 'write'
    steps:
      - uses: 'goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757' # ratchet:goreleaser/goreleaser-action@v3
        with:
          version: 'latest'
          args: 'release --rm-dist'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
