name: 'release'

on:
  push:
    tags:
      - 'v*'
env:
  SOURCE_DOCKER_IMAGE: 'us-docker.pkg.dev/lumberjack-dev-infra/images/lumberjack-server:${{ github.sha }}'
  TARGET_DOCKER_IMAGE: 'us-docker.pkg.dev/abcxyz-artifacts/docker-images/lumberjack-server:${{ github.ref_name }}'
  WIF_PROVIDER: 'projects/638387980668/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
  WIF_SERVICE_ACCOUNT: 'gh-access-sa@lumberjack-dev-infra.iam.gserviceaccount.com'

# Don't cancel in progress since we don't want to have half-baked release.
concurrency: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-release'

jobs:
  ci-test:
    uses: 'abcxyz/lumberjack/.github/workflows/ci.yml@main' # ratchet:exclude

  image-release:
    # Run tests before the release
    needs: ['ci-test']
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@c4799db9111fba4461e9f9da8732e5057b394f72' # ratchet:google-github-actions/auth@v0
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@62d4898025f6041e16b1068643bfc5a696863587' # ratchet:google-github-actions/setup-gcloud@v1

      - name: 'Copy images to Release registry'
        run: |-
          gcloud container images add-tag --quiet ${{ env.SOURCE_DOCKER_IMAGE }}-amd64 ${{ env.TARGET_DOCKER_IMAGE }}-amd64
          gcloud container images add-tag --quiet ${{ env.SOURCE_DOCKER_IMAGE }}-arm64 ${{ env.TARGET_DOCKER_IMAGE }}-arm64
          gcloud container images add-tag --quiet ${{ env.SOURCE_DOCKER_IMAGE }} ${{ env.TARGET_DOCKER_IMAGE }}

  maven-release:
    # Run tests before the release
    needs: ['ci-test']
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b' # ratchet:actions/checkout@v3

      - uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # ratchet:actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: 'google-github-actions/auth@c4799db9111fba4461e9f9da8732e5057b394f72' # ratchet:google-github-actions/auth@v0
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
          # The Artifact Registry maven wagon looks for Google Application Default Credentials.
          # https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools

      - name: 'Maven deploy'
        # Use git tag without prefix "v".
        # Even though Artifact Registry allows versions starts with "v",
        # Maven's convention is to have versions without "v".
        run: |-
          mvn clean deploy -Drevision=$(echo '${{ github.ref_name }}' | cut -c 2-) -f clients/java-logger/library

  github-release:
    needs: ['image-release', 'maven-release']
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
      packages: 'write'
    steps:
      - uses: 'actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b' # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: 'actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568' # ratchet:actions/setup-go@v3
        with:
          go-version: '1.20'

      - uses: 'goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757' # ratchet:goreleaser/goreleaser-action@v3
        with:
          version: 'v1.16.1' # Manually pinned
          args: 'release --clean'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
