name: 'Test Go client'

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/test-go-client.yml'
      - 'clients/go/**.go'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/test-go-client.yml'
      - 'clients/go/**.go'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    uses: 'abcxyz/pkg/.github/workflows/go-test.yml@main'
    with:
      go_version: '1.18'
      directory: 'clients/go'
      go_packages: './...'
