name: 'unit_and_lint'
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  # Linting jobs
  terraform_lint:
    uses: 'abcxyz/pkg/.github/workflows/terraform-lint.yml@cc2b918b16df0f627b933ed8dddf0d846fa9108b' # ratchet:abcxyz/pkg/.github/workflows/terraform-lint.yml@main
    with:
      directory: 'terraform'
      terraform_version: '1.2'
  go_lint_cmd:
    uses: 'abcxyz/pkg/.github/workflows/go-lint.yml@cc2b918b16df0f627b933ed8dddf0d846fa9108b' # ratchet:abcxyz/pkg/.github/workflows/go-lint.yml@main
    with:
      directory: 'cmd'
      go_version: '1.19'
  go_lint_pkg:
    uses: 'abcxyz/pkg/.github/workflows/go-lint.yml@cc2b918b16df0f627b933ed8dddf0d846fa9108b' # ratchet:abcxyz/pkg/.github/workflows/go-lint.yml@main
    with:
      directory: 'pkg'
      go_version: '1.19'
  go_lint_integration:
    uses: 'abcxyz/pkg/.github/workflows/go-lint.yml@cc2b918b16df0f627b933ed8dddf0d846fa9108b' # ratchet:abcxyz/pkg/.github/workflows/go-lint.yml@main
    with:
      directory: 'integration'
      go_version: '1.19'
  java_lint:
    uses: 'abcxyz/pkg/.github/workflows/java-lint.yml@cc2b918b16df0f627b933ed8dddf0d846fa9108b' # ratchet:abcxyz/pkg/.github/workflows/java-lint.yml@main
    with:
      directory: 'clients/java-logger'
      java_version: '11'

  # Unit tests
  go_test:
    uses: 'abcxyz/pkg/.github/workflows/go-test.yml@cc2b918b16df0f627b933ed8dddf0d846fa9108b' # ratchet:abcxyz/pkg/.github/workflows/go-test.yml@main
    with:
      go_version: '1.19'
      go_packages: |-
        $(go list ./... | grep -v -E 'lumberjack/third_party|lumberjack/integration')
  java_test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8' # ratchet:actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d # ratchet:actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run tests with Maven
        run: |-
          mvn clean test --no-transfer-progress -f clients/java-logger

# TODO: enable coverage for java
# cover: no required module provides package github.com/abcxyz/lumberjack/clients/go/pkg/audit:
# go.mod file not found in current directory or any parent directory; see 'go help modules'
# - name: go-coverage
#   shell: bash
#   run: |-
#     OUTPUT="$(go tool cover -func=./clients/go/coverage.out)"
#     TOTAL="$(echo $OUTPUT | awk 'END{print $NF}')"
#     echo "::group::Coverage (${TOTAL})"
#     echo "${OUTPUT}"
#     echo "::endgroup::"
